// this is a comment
$define
    $int x:=50
    $string hello := "hello"
    $string world := "world"
    $string str := "logo"
$begin
    $turn(right,90)
    $if(x>10) $begin
        $move(forward,x)
        $print(hello)
        $if (100 > x) $begin
            $move(forward,x)
            $print(world)
        $end
    $end

    $for (100) $begin
        $move(forward,repcount * 2)
        $turn(right,90)
    $end

    $turn(left,90)
    $move(forward,x*2)
    $print(str)
$end
